### ISSUE TITLE
Medium.com buttons

### ISSUE THREAD

**Issue by vincetse** [timhuisman/css-social-media-buttons#13]
Hey there, @timhuisman, any chance you can make some buttons for [Medium](https://medium.com/)?  I'd love to send a PR, but I can't for the life of me figure out how to create the icons.  Thanks in advance!

**Comment by timhuisman** [comment]
Hey @vincetse,

I'm currently working on version 3, in which I added multiple new buttons including one for Medium (green background with greyish logo). So you just have to wait a little bit.

**Comment by timhuisman** [comment]
Hello @vincetse 

I've just released version 3 in which I added the Medium button. I've hope you like it!
